import React, { useState } from 'react';
import { useReport } from '../hooks/use-report';
import type { ReportType } from '../api/report-api';
import { ReportSkeleton } from '../components/report-skeleton';
import { ReportHeader } from '../components/report-header';
import { ReportPlatformOverviewCard } from '../components/report-platform-overview';
import { ReportThreatIntelligenceCard } from '../components/report-threat-intelligence';
import { ReportInvestigationsCard } from '../components/report-investigations';
import { ReportFeedStatisticsCard } from '../components/report-feed-statistics';

export const ReportsPage: React.FC = () => {
  const [selectedType, setSelectedType] = useState<ReportType>('daily');
  const { data: report, isLoading, error } = useReport(selectedType);

  const reportTypes: { id: ReportType; label: string }[] = [
    { id: 'daily', label: 'Daily' },
    { id: 'weekly', label: 'Weekly' },
    { id: 'monthly', label: 'Monthly' },
    { id: 'executive', label: 'Executive' },
  ];

  return (
    <div className="flex-1 flex flex-col h-full overflow-y-auto">
      {/* Page Header */}
      <div className="px-6 py-4 border-b border-border flex items-center justify-between bg-card/30 flex-shrink-0">
        <div>
          <h1 className="text-base font-semibold tracking-tight">Intelligence Reports</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Structured view of intelligence reports generated by the platform
          </p>
        </div>

        <div className="flex items-center bg-secondary rounded-md p-0.5 border border-border">
          {reportTypes.map((type) => (
            <button
              key={type.id}
              onClick={() => setSelectedType(type.id)}
              className={`px-3 py-1.5 text-xs font-medium rounded-sm transition-colors ${
                selectedType === type.id
                  ? 'bg-background shadow-sm text-foreground'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 p-6">
        {isLoading ? (
          <ReportSkeleton />
        ) : error || !report ? (
          <div className="p-12 text-center border border-dashed border-border rounded-lg bg-card/50">
            <div className="text-destructive mb-1 font-semibold text-sm">Failed to load report</div>
            <p className="text-muted-foreground text-xs">
              {error instanceof Error ? error.message : 'Unknown error occurred while generating the report.'}
            </p>
          </div>
        ) : (
          <div className="space-y-4 animate-in fade-in duration-300">
            <ReportHeader report={report} reportType={selectedType} />
            <ReportPlatformOverviewCard overview={report.platform_overview} />

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 items-start">
              <div className="space-y-4">
                <ReportThreatIntelligenceCard intel={report.threat_intelligence} />
                <ReportFeedStatisticsCard stats={report.feed_statistics} />
              </div>
              <div className="space-y-4">
                <ReportInvestigationsCard investigations={report.investigations} />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
