import React, { useState } from 'react';
import { useReport } from '../hooks/use-report';
import type { ReportType } from '../api/report-api';
import { ReportSkeleton } from '../components/report-skeleton';
import { ReportHeader } from '../components/report-header';
import { ReportPlatformOverviewCard } from '../components/report-platform-overview';
import { ReportThreatIntelligenceCard } from '../components/report-threat-intelligence';
import { ReportInvestigationsCard } from '../components/report-investigations';
import { ReportFeedStatisticsCard } from '../components/report-feed-statistics';

export const ReportsPage: React.FC = () => {
  const [selectedType, setSelectedType] = useState<ReportType>('daily');
  const { data: report, isLoading, error } = useReport(selectedType);

  const reportTypes: { id: ReportType; label: string }[] = [
    { id: 'daily', label: 'Daily Report' },
    { id: 'weekly', label: 'Weekly Report' },
    { id: 'monthly', label: 'Monthly Report' },
    { id: 'executive', label: 'Executive Summary' },
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto w-full h-full flex flex-col overflow-hidden">
      <div className="flex items-center justify-between mb-6 flex-shrink-0">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Intelligence Reports</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Structured view of intelligence reports generated by the platform.
          </p>
        </div>
        
        <div className="flex items-center bg-secondary rounded-lg p-1 border border-border">
          {reportTypes.map((type) => (
            <button
              key={type.id}
              onClick={() => setSelectedType(type.id)}
              className={`px-4 py-1.5 text-sm font-medium rounded-md transition-colors ${
                selectedType === type.id 
                  ? 'bg-background shadow-sm text-foreground' 
                  : 'text-muted-foreground hover:text-foreground hover:bg-background/50'
              }`}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto pb-6">
        {isLoading ? (
          <ReportSkeleton />
        ) : error || !report ? (
          <div className="p-12 text-center border border-dashed border-border rounded-lg bg-card/50">
            <div className="text-destructive mb-2 font-semibold">Failed to load report</div>
            <p className="text-muted-foreground text-sm">
              {error instanceof Error ? error.message : 'Unknown error occurred while generating the report.'}
            </p>
          </div>
        ) : (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <ReportHeader report={report} reportType={selectedType} />
            <ReportPlatformOverviewCard overview={report.platform_overview} />
            
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
              <ReportThreatIntelligenceCard intel={report.threat_intelligence} />
              <div className="space-y-6">
                <ReportInvestigationsCard investigations={report.investigations} />
                <ReportFeedStatisticsCard stats={report.feed_statistics} />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
