"""Index on risk_score_int

Revision ID: 302b781de2a2
Revises: 430f4f93de51
Create Date: 2026-07-15 09:43:19.635679

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '302b781de2a2'
down_revision: str | None = '430f4f93de51'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_indicators_risk_score'), 'indicators', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_risk_score'), table_name='indicators')
    # ### end Alembic commands ###
