"""Index on risk_score

Revision ID: 430f4f93de51
Revises: b6d376c25f60
Create Date: 2026-07-15 09:42:24.951492

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '430f4f93de51'
down_revision: str | None = 'b6d376c25f60'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
