"""investigation_engine

Revision ID: 5acb6156270b
Revises: ea271c0b7cde
Create Date: 2026-07-02 06:47:33.468112

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5acb6156270b'
down_revision: str | None = 'ea271c0b7cde'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation_indicator', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation_indicator', 'created_at')
    # ### end Alembic commands ###
