"""database_foundation

Revision ID: 6d4d4982970a
Revises: 
Create Date: 2026-06-30 09:33:13.633461

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6d4d4982970a'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='AssetType enum stored as string'),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False, comment='AssetCriticality enum stored as string'),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index(op.f('ix_assets_value'), 'assets', ['value'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_sector', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('target_country', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=True)
    op.create_table('feeds',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False, comment='FeedType enum stored as string'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('authentication', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='FeedStatus enum stored as string'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_name'), 'feeds', ['name'], unique=True)
    op.create_index(op.f('ix_feeds_status'), 'feeds', ['status'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='IndicatorType enum value stored as string'),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity enum value stored as string'),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='IndicatorStatus enum value stored as string'),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('asn', sa.String(length=20), nullable=True),
    sa.Column('whois', sa.JSON(), nullable=True),
    sa.Column('passive_dns', sa.JSON(), nullable=True),
    sa.Column('reputation', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_indicator_confidence'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_indicator_risk_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indicator_type_normalized_value', 'indicators', ['type', 'normalized_value'], unique=True)
    op.create_index(op.f('ix_indicators_country'), 'indicators', ['country'], unique=False)
    op.create_index(op.f('ix_indicators_normalized_value'), 'indicators', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_indicators_status'), 'indicators', ['status'], unique=False)
    op.create_index(op.f('ix_indicators_type'), 'indicators', ['type'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='InvestigationStatus enum stored as string'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='InvestigationPriority enum stored as string'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_owner'), 'investigations', ['owner'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_title'), 'investigations', ['title'], unique=False)
    op.create_table('malware',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('persistence', sa.Text(), nullable=True),
    sa.Column('communication', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malware_category'), 'malware', ['category'], unique=False)
    op.create_index(op.f('ix_malware_name'), 'malware', ['name'], unique=True)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_tactic'), 'mitre_techniques', ['tactic'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_technique_id'), 'mitre_techniques', ['technique_id'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.create_table('threat_actors',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('sophistication', sa.String(length=20), nullable=False, comment='ThreatActorSophistication enum stored as string'),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_actors_country'), 'threat_actors', ['country'], unique=False)
    op.create_index(op.f('ix_threat_actors_name'), 'threat_actors', ['name'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('cve', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('exploited', sa.Boolean(), nullable=False),
    sa.Column('patch_available', sa.Boolean(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve'), 'vulnerabilities', ['cve'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('matching_rule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=False)
    op.create_index(op.f('ix_watchlists_owner'), 'watchlists', ['owner'], unique=False)
    op.create_table('campaign_mitre_technique',
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('technique_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'technique_id')
    )
    op.create_table('campaign_report',
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'report_id')
    )
    op.create_table('campaign_vulnerability',
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('vulnerability_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'vulnerability_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False, comment='CommentEntityType enum stored as string'),
    sa.Column('investigation_id', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_comments_investigation_id'), 'comments', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_comments_report_id'), 'comments', ['report_id'], unique=False)
    op.create_table('feed_runs',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('feed_id', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='FeedRunStatus enum stored as string'),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_runs_feed_id'), 'feed_runs', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_runs_status'), 'feed_runs', ['status'], unique=False)
    op.create_table('indicator_asset',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'asset_id')
    )
    op.create_table('indicator_campaign',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'campaign_id')
    )
    op.create_table('indicator_feed',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('feed_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'feed_id')
    )
    op.create_table('indicator_malware',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'malware_id')
    )
    op.create_table('indicator_mitre_technique',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('technique_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'technique_id')
    )
    op.create_table('indicator_report',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'report_id')
    )
    op.create_table('indicator_threat_actor',
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'threat_actor_id')
    )
    op.create_table('investigation_asset',
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'asset_id')
    )
    op.create_table('investigation_campaign',
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'campaign_id')
    )
    op.create_table('investigation_indicator',
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'indicator_id')
    )
    op.create_table('investigation_malware',
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'malware_id')
    )
    op.create_table('investigation_threat_actor',
    sa.Column('investigation_id', sa.Text(), nullable=False),
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'threat_actor_id')
    )
    op.create_table('malware_campaign',
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('malware_id', 'campaign_id')
    )
    op.create_table('malware_mitre_technique',
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.Column('technique_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('malware_id', 'technique_id')
    )
    op.create_table('malware_report',
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('malware_id', 'report_id')
    )
    op.create_table('threat_actor_campaign',
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'campaign_id')
    )
    op.create_table('threat_actor_malware',
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'malware_id')
    )
    op.create_table('threat_actor_mitre_technique',
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.Column('technique_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'technique_id')
    )
    op.create_table('threat_actor_report',
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'report_id')
    )
    op.create_table('vulnerability_malware',
    sa.Column('vulnerability_id', sa.Text(), nullable=False),
    sa.Column('malware_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vulnerability_id', 'malware_id')
    )
    op.create_table('vulnerability_threat_actor',
    sa.Column('vulnerability_id', sa.Text(), nullable=False),
    sa.Column('threat_actor_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vulnerability_id', 'threat_actor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability_threat_actor')
    op.drop_table('vulnerability_malware')
    op.drop_table('threat_actor_report')
    op.drop_table('threat_actor_mitre_technique')
    op.drop_table('threat_actor_malware')
    op.drop_table('threat_actor_campaign')
    op.drop_table('malware_report')
    op.drop_table('malware_mitre_technique')
    op.drop_table('malware_campaign')
    op.drop_table('investigation_threat_actor')
    op.drop_table('investigation_malware')
    op.drop_table('investigation_indicator')
    op.drop_table('investigation_campaign')
    op.drop_table('investigation_asset')
    op.drop_table('indicator_threat_actor')
    op.drop_table('indicator_report')
    op.drop_table('indicator_mitre_technique')
    op.drop_table('indicator_malware')
    op.drop_table('indicator_feed')
    op.drop_table('indicator_campaign')
    op.drop_table('indicator_asset')
    op.drop_index(op.f('ix_feed_runs_status'), table_name='feed_runs')
    op.drop_index(op.f('ix_feed_runs_feed_id'), table_name='feed_runs')
    op.drop_table('feed_runs')
    op.drop_index(op.f('ix_comments_report_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_investigation_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('campaign_vulnerability')
    op.drop_table('campaign_report')
    op.drop_table('campaign_mitre_technique')
    op.drop_index(op.f('ix_watchlists_owner'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_vulnerabilities_cve'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_threat_actors_name'), table_name='threat_actors')
    op.drop_index(op.f('ix_threat_actors_country'), table_name='threat_actors')
    op.drop_table('threat_actors')
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_mitre_techniques_technique_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_tactic'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_malware_name'), table_name='malware')
    op.drop_index(op.f('ix_malware_category'), table_name='malware')
    op.drop_table('malware')
    op.drop_index(op.f('ix_investigations_title'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_owner'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_indicators_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_status'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_normalized_value'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_country'), table_name='indicators')
    op.drop_index('ix_indicator_type_normalized_value', table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_feeds_status'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_name'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_assets_value'), table_name='assets')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
