"""add_needs_scoring_to_indicators

Revision ID: 761f85c4b313
Revises: f1b2c3d4e5f6
Create Date: 2026-07-14 12:20:09.455844

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '761f85c4b313'
down_revision: str | None = 'f1b2c3d4e5f6'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('needs_scoring', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_indicators_needs_scoring'), 'indicators', ['needs_scoring'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_needs_scoring'), table_name='indicators')
    op.drop_column('indicators', 'needs_scoring')
    # ### end Alembic commands ###
