"""add risk_score_version to indicators

Revision ID: 77c326e9c1a7
Revises: 761f85c4b313
Create Date: 2026-07-14 12:55:19.124010

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '77c326e9c1a7'
down_revision: str | None = '761f85c4b313'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('risk_score_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'risk_score_version')
    # ### end Alembic commands ###
