"""add scoring status fields

Revision ID: 8e227a23dd83
Revises: 77c326e9c1a7
Create Date: 2026-07-15 04:20:33.261184

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e227a23dd83'
down_revision: str | None = '77c326e9c1a7'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('indicators', sa.Column('scoring_failed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('indicators', sa.Column('last_scoring_error', sa.Text(), nullable=True))
    op.add_column('indicators', sa.Column('last_scoring_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'last_scoring_attempt_at')
    op.drop_column('indicators', 'last_scoring_error')
    op.drop_column('indicators', 'scoring_failed')
    op.drop_column('indicators', 'scored_at')
    # ### end Alembic commands ###
