"""watchlists

Revision ID: 989320b0dc22
Revises: 5acb6156270b
Create Date: 2026-07-02 10:42:53.061832

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '989320b0dc22'
down_revision: str | None = '5acb6156270b'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_matches',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('watchlist_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'entity_type', 'entity_id', name='uq_watchlist_match')
    )
    op.create_index(op.f('ix_watchlist_matches_entity_id'), 'watchlist_matches', ['entity_id'], unique=False)
    op.create_index(op.f('ix_watchlist_matches_entity_type'), 'watchlist_matches', ['entity_type'], unique=False)
    op.create_index(op.f('ix_watchlist_matches_watchlist_id'), 'watchlist_matches', ['watchlist_id'], unique=False)
    op.drop_index('ix_indicator_confidence', table_name='indicators')
    op.drop_index('ix_indicator_first_seen', table_name='indicators')
    op.drop_index('ix_indicator_last_seen', table_name='indicators')
    op.drop_index('ix_indicator_source_count', table_name='indicators')
    op.add_column('watchlists', sa.Column('watchlist_type', sa.String(length=50), nullable=False))
    op.add_column('watchlists', sa.Column('values', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.alter_column('watchlists', 'matching_rule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_index('ix_watchlists_owner', table_name='watchlists')
    op.create_index(op.f('ix_watchlists_watchlist_type'), 'watchlists', ['watchlist_type'], unique=False)
    op.drop_column('watchlists', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_watchlists_watchlist_type'), table_name='watchlists')
    op.create_index('ix_watchlists_owner', 'watchlists', ['owner'], unique=False)
    op.alter_column('watchlists', 'matching_rule',
               existing_type=sa.String(length=50),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('watchlists', 'values')
    op.drop_column('watchlists', 'watchlist_type')
    op.create_index('ix_indicator_source_count', 'indicators', ['source_count'], unique=False)
    op.create_index('ix_indicator_last_seen', 'indicators', ['last_seen'], unique=False)
    op.create_index('ix_indicator_first_seen', 'indicators', ['first_seen'], unique=False)
    op.create_index('ix_indicator_confidence', 'indicators', ['confidence'], unique=False)
    op.drop_index(op.f('ix_watchlist_matches_watchlist_id'), table_name='watchlist_matches')
    op.drop_index(op.f('ix_watchlist_matches_entity_type'), table_name='watchlist_matches')
    op.drop_index(op.f('ix_watchlist_matches_entity_id'), table_name='watchlist_matches')
    op.drop_table('watchlist_matches')
    # ### end Alembic commands ###
