"""Add watchlist rules and alerts

Revision ID: b6d376c25f60
Revises: f72a6b54eff9
Create Date: 2026-07-15 07:39:27.124053

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b6d376c25f60'
down_revision: str | None = 'f72a6b54eff9'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_alerts',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('watchlist_id', sa.Text(), nullable=False),
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score_snapshot', sa.Float(), nullable=True),
    sa.Column('matched_rule', sa.Text(), nullable=True),
    sa.Column('matched_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'indicator_id', name='uq_watchlist_alert')
    )
    op.create_index(op.f('ix_watchlist_alerts_indicator_id'), 'watchlist_alerts', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_watchlist_alerts_watchlist_id'), 'watchlist_alerts', ['watchlist_id'], unique=False)
    op.create_table('watchlist_rules',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('watchlist_id', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_rules_watchlist_id'), 'watchlist_rules', ['watchlist_id'], unique=False)
    op.drop_index('ix_watchlist_matches_entity_id', table_name='watchlist_matches')
    op.drop_index('ix_watchlist_matches_entity_type', table_name='watchlist_matches')
    op.drop_index('ix_watchlist_matches_watchlist_id', table_name='watchlist_matches')
    op.drop_table('watchlist_matches')
    op.drop_index('ix_watchlists_watchlist_type', table_name='watchlists')
    op.drop_column('watchlists', 'values')
    op.drop_column('watchlists', 'watchlist_type')
    op.drop_column('watchlists', 'matching_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('matching_rule', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('watchlists', sa.Column('watchlist_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('watchlists', sa.Column('values', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False))
    op.create_index('ix_watchlists_watchlist_type', 'watchlists', ['watchlist_type'], unique=False)
    op.create_table('watchlist_matches',
    sa.Column('id', sa.TEXT(), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('watchlist_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('match_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name='watchlist_matches_watchlist_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='watchlist_matches_pkey'),
    sa.UniqueConstraint('watchlist_id', 'entity_type', 'entity_id', name='uq_watchlist_match')
    )
    op.create_index('ix_watchlist_matches_watchlist_id', 'watchlist_matches', ['watchlist_id'], unique=False)
    op.create_index('ix_watchlist_matches_entity_type', 'watchlist_matches', ['entity_type'], unique=False)
    op.create_index('ix_watchlist_matches_entity_id', 'watchlist_matches', ['entity_id'], unique=False)
    op.drop_index(op.f('ix_watchlist_rules_watchlist_id'), table_name='watchlist_rules')
    op.drop_table('watchlist_rules')
    op.drop_index(op.f('ix_watchlist_alerts_watchlist_id'), table_name='watchlist_alerts')
    op.drop_index(op.f('ix_watchlist_alerts_indicator_id'), table_name='watchlist_alerts')
    op.drop_table('watchlist_alerts')
    # ### end Alembic commands ###
