"""enrichment_engine

Revision ID: ea271c0b7cde
Revises: 830382a8ded4
Create Date: 2026-07-02 05:34:04.358609

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ea271c0b7cde'
down_revision: str | None = '830382a8ded4'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_results',
    sa.Column('id', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('indicator_id', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('extracted_attributes', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(length=30), nullable=False, comment='EnrichmentStatus enum value stored as string'),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_results_execution_status'), 'enrichment_results', ['execution_status'], unique=False)
    op.create_index(op.f('ix_enrichment_results_indicator_id'), 'enrichment_results', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_enrichment_results_provider'), 'enrichment_results', ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_enrichment_results_provider'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_indicator_id'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_execution_status'), table_name='enrichment_results')
    op.drop_table('enrichment_results')
    # ### end Alembic commands ###
