"""Add entity_events table

Revision ID: f72a6b54eff9
Revises: 8aa28c9a4b17
Create Date: 2026-07-15 07:02:19.806790

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f72a6b54eff9'
down_revision: str | None = '8aa28c9a4b17'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_events_entity_created_at', 'entity_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_entity_events_entity_id'), 'entity_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_events_entity_type'), 'entity_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_events_event_type'), 'entity_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_events_event_type'), table_name='entity_events')
    op.drop_index(op.f('ix_entity_events_entity_type'), table_name='entity_events')
    op.drop_index(op.f('ix_entity_events_entity_id'), table_name='entity_events')
    op.drop_index('ix_entity_events_entity_created_at', table_name='entity_events')
    op.drop_table('entity_events')
    # ### end Alembic commands ###
